name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 52.16.194.174
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Stop existing Node.js server
            PID=$(sudo lsof -t -i:5501)
            if [ ! -z "$PID" ]; then
              sudo kill -9 $PID
            fi
            # Remove previous repository
            rm -rf kindness-Frontend
            # Clone new repository
            git clone https://github.com/enjoyimkrsnna/kindness-Frontend
            # Start Node.js server
            nohup node server.js > output.log 2>&1 &

      - name: Zip and Copy to S3
        run: |
          # Check if the kindness-Frontend directory exists
          if [ -d "kindness-Frontend" ]; then
            # Zip the kindness-Frontend folder
            zip -r kindness-Frontend.zip kindness-Frontend
            # Copy the zip file to S3
            aws s3 cp kindness-Frontend.zip s3://unique-kindnesskettle-image/Frontend/
          else
            echo "Directory kindness-Frontend does not exist. Skipping zip and copy to S3."
          fi
